version: '3'
services:
    app:
        build: ./app
        ports:
            - 3000:3000
    server:
        build: ./server
        environment:
            POSTGRES_PASSWORD: password
            POSTGRES_USER: postgres
            POSTGRES_DB: ohohoh
            POSTGRES_HOST: db_1,
        ports:
            - 3001:3001

    db:
        image: postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
        ports:
            - 5432:5432